const router = require('express').Router()
const regc = require('../controllers/regcontroller')
const bannerc = require('../controllers/bannercontroller')
const servicec = require('../controllers/servicecontroller')
const testic = require('../controllers/testicontroller')
const queryc = require('../controllers/querycontroller')
const addc = require('../controllers/addcontroller')
const upload = require('../helpers/multer')
const handlelogin = require('../helpers/logincheck')


router.get('/', regc.loginpage)
router.post('/', regc.logincheck)
router.get('/dashboard', regc.dashboard)
router.get('/logout', regc.logout)
router.get('/banner', bannerc.bannerpage)
router.get('/bannerupdateform/:id', bannerc.bannerform)
router.post('/bannerupdateform/:id', upload.single('img'), bannerc.bannerupdate)
router.get('/service', servicec.servicepage)
router.get('/addservice', servicec.serviceform)
router.post('/addservice', upload.single('img'), servicec.serviceadd)
router.get('/servicedelete/:id', servicec.servicedelete)
router.get('/servicestatusupdate/:id', servicec.servicestatusupdate)
router.get('/testi', testic.testipage)
router.post('/testi', testic.search)
router.get('/testistatusupdate/:id', testic.testistatusupdate)
router.get('/testidelete/:id', testic.testidelete)
router.get('/query', queryc.querypage)
router.get('/queryreply/:id', queryc.emailpage)
router.post('/queryreply/:id', upload.single('attachement'), queryc.sendmail)
router.post('/service', servicec.search)
router.get('/emaildelete/:id', queryc.deleteemail)
router.get('/address', addc.addaddress)
router.get('/addupdate/:id', addc.updateform)
router.post('/addupdate/:id', addc.addupdate)


module.exports = router
